version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - aws --version
      - aws cloudformation deploy --template-file "$template" --stack-name "$stack_name" --capabilities CAPABILITY_NAMED_IAM --parameter-overrides EKSIAMRoleName=EKSServiceRole EKSClusterName=PerformanceTestingControlPlane