version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - echo Deploying...
      - aws cloudformation deploy --template-file templates/eks_control_plane.yml --stack-name PerformanceTestingEKSControlPlane --capabilities CAPABILITY_NAMED_IAM --parameter-overrides EKSIAMRoleName=EKSServiceRole EKSClusterName=PerformanceTestingControlPlane
