version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - aws --version
      - aws cloudformation deploy --template-file templates/ecr.yml --stack-name PerformanceTestBlueprint-HelmRepo --parameter-overrides RepositoryName=performance-test-blueprint-chart