AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Cloudformation for creating a Manual Load Testing Environment'

Parameters:
  RepositoryName:
    Type: String

Resources:
  LocustImageRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Ref RepositoryName

