AWSTemplateFormatVersion: '2010-09-09'
Description: 'Report storage stack for performance testing reports'

Parameters:
  PerformanceReportsS3Bucket:
    Type: String

Resources:
  ReportS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref PerformanceReportsS3Bucket
